# Generated by Django 4.2.7 on 2023-12-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
