# Generated by Django 4.2.7 on 2023-12-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('False', 'False')], default='False', max_length=10),
        ),
    ]
