# Generated by Django 4.2.7 on 2023-12-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayir')], max_length=10),
        ),
    ]
