# Generated by Django 4.2.7 on 2023-12-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ok'), (False, 'No')], default=False),
        ),
    ]
