# Generated by Django 4.2.7 on 2023-12-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_replycomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='post',
            new_name='post_id',
        ),
    ]
