# Generated by Django 4.2.7 on 2023-12-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_post_replycomment_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='post_id',
            new_name='post',
        ),
    ]
