# Generated by Django 4.2.7 on 2023-12-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_post_id_replycomment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replycomment',
            name='post',
        ),
    ]
