# Generated by Django 4.2.7 on 2023-12-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_replycomment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='repcomment',
            new_name='comment',
        ),
    ]
