# Generated by Django 4.2.7 on 2023-12-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_replycomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), (True, 'True'), (False, 'False')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), (True, 'True'), (False, 'False')], default='New', max_length=10),
        ),
    ]
