# Generated by Django 4.2.7 on 2023-12-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_comment_status_alter_replycomment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(choices=[('New', 'New'), (True, 'Ok'), (False, 'No')], default='New'),
        ),
    ]
