# Generated by Django 4.2.7 on 2023-12-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[(True, 'Ok'), (False, 'No')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ok'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='status',
            field=models.CharField(choices=[(True, 'Ok'), (False, 'No')], default=False, max_length=10),
        ),
    ]
