# Generated by Django 4.2.7 on 2023-12-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_comment_status_alter_replycomment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('true', 'Ok'), ('false', 'No')], default='new', max_length=5),
        ),
    ]
