# Generated by Django 4.2.7 on 2023-12-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'Ok'), ('False', 'No')], default='New', max_length=5),
        ),
    ]
